# Generated by Django 5.1.1 on 2024-11-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='image_1',
            field=models.ImageField(default='No Image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_1_path',
            field=models.CharField(default='No Image', max_length=1024),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_2',
            field=models.ImageField(default='No Image', upload_to=''),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_2_path',
            field=models.CharField(default='No Image', max_length=1024),
        ),
    ]
