# Generated by Django 5.1.1 on 2024-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='image_1_url',
        ),
        migrations.RemoveField(
            model_name='print',
            name='image_2_url',
        ),
        migrations.AddField(
            model_name='print',
            name='image_1_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='print',
            name='image_2_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
