# Generated by Django 5.1.1 on 2024-10-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_print_image_1_url_remove_print_image_2_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
