# Generated by Django 5.1.1 on 2024-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print',
            name='image_1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_1_path',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='print',
            name='image_2_path',
            field=models.CharField(max_length=1024),
        ),
    ]
